# Generated by Django 2.2 on 2019-06-20 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190620_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 23, 4, 27, 166268), verbose_name='Date'),
        ),
    ]
