# Generated by Django 2.2 on 2019-06-20 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20190619_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_photo',
            old_name='profile',
            new_name='profile_id',
        ),
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 1, 47, 23, 538821), verbose_name='Date'),
        ),
    ]
