# Generated by Django 2.2 on 2019-06-20 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190620_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 6, 20, 18, 32, 7, 533261), verbose_name='Date'),
        ),
    ]
